create user test identified by 111111;
grant create sessinn to test;

--------------------------------------------------------
--  文件已创建 - 星期五-七月-14-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence S_ANSWER
--------------------------------------------------------

   CREATE SEQUENCE  "TEST"."S_ANSWER"  MINVALUE 1 MAXVALUE 9999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence S_INFO
--------------------------------------------------------

   CREATE SEQUENCE  "TEST"."S_INFO"  MINVALUE 1 MAXVALUE 9999999999999 INCREMENT BY 1 START WITH 301 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence T_ANSWER
--------------------------------------------------------

   CREATE SEQUENCE  "TEST"."T_ANSWER"  MINVALUE 1 MAXVALUE 999999999999999 INCREMENT BY 1 START WITH 441 CACHE 20 ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence T_PAPER
--------------------------------------------------------

   CREATE SEQUENCE  "TEST"."T_PAPER"  MINVALUE 1 MAXVALUE 99999999999999 INCREMENT BY 1 START WITH 121 CACHE 20 ORDER  NOCYCLE ;
--------------------------------------------------------
--  文件已创建 - 星期五-七月-14-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table INFO_PAPER
--------------------------------------------------------

  CREATE TABLE "TEST"."INFO_PAPER" 
   (	"STU_INFO_ID" VARCHAR2(20 BYTE), 
	"TEST_PAPER_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STU_ANSWER
--------------------------------------------------------

  CREATE TABLE "TEST"."STU_ANSWER" 
   (	"STU_ANSWER_ID" VARCHAR2(20 BYTE), 
	"STU_ANSWER_NO" VARCHAR2(20 BYTE), 
	"STU_ANSWER_ANS" VARCHAR2(20 BYTE), 
	"STU_ANSWER_GRADE" VARCHAR2(20 BYTE), 
	"TEST_PAPER_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STU_INFO
--------------------------------------------------------

  CREATE TABLE "TEST"."STU_INFO" 
   (	"STU_INFO_ID" VARCHAR2(20 BYTE), 
	"STU_INFO_NAME" VARCHAR2(20 BYTE), 
	"STU_INFO_GRADE" VARCHAR2(20 BYTE), 
	"STU_INFO_IDENTITY" VARCHAR2(20 BYTE), 
	"STU_INFO_TICKET" VARCHAR2(20 BYTE), 
	"STU_INFO_STA" VARCHAR2(20 BYTE), 
	"STU_INFO_NO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TB_TEACHER
--------------------------------------------------------

  CREATE TABLE "TEST"."TB_TEACHER" 
   (	"ID" VARCHAR2(20 BYTE), 
	"T_NAME" VARCHAR2(20 BYTE), 
	"T_ACCOUNT" VARCHAR2(20 BYTE), 
	"T_PWD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TEST_ANSWER
--------------------------------------------------------

  CREATE TABLE "TEST"."TEST_ANSWER" 
   (	"TEST_ANSWER_ID" VARCHAR2(255 BYTE), 
	"TEST_ANSWER_NO" VARCHAR2(255 BYTE), 
	"TEST_ANSWER_ANS" VARCHAR2(255 BYTE), 
	"TEST_ANSWER_GRADE" VARCHAR2(255 BYTE), 
	"TEST_ANSWER_TYPE" VARCHAR2(255 BYTE), 
	"TEST_ANSWER_TIGAN" VARCHAR2(255 BYTE), 
	"TEST_ANSWER_A" VARCHAR2(255 BYTE), 
	"TEST_ANSWER_B" VARCHAR2(255 BYTE), 
	"TEST_ANSWER_C" VARCHAR2(255 BYTE), 
	"TEST_ANSWER_D" VARCHAR2(255 BYTE), 
	"TEST_PAPER_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TEST_PAPER
--------------------------------------------------------

  CREATE TABLE "TEST"."TEST_PAPER" 
   (	"TEST_PAPER_ID" VARCHAR2(255 BYTE), 
	"TEST_PAPER_NAME" VARCHAR2(255 BYTE), 
	"TEST_PAPER_GRADE" VARCHAR2(255 BYTE), 
	"TEST_PAPER_WORK" VARCHAR2(255 BYTE), 
	"TEST_PAPER_TYPE" VARCHAR2(255 BYTE), 
	"TEST_PAPER_LEVEL" VARCHAR2(255 BYTE), 
	"TEST_PAPER_TIME" VARCHAR2(255 BYTE), 
	"TEST_PAPER_MECHANISM" VARCHAR2(255 BYTE), 
	"TEST_PAPER_TEST" VARCHAR2(255 BYTE), 
	"TEST_PAPER_SINGLE" VARCHAR2(255 BYTE), 
	"TEST_PAPER_MULTIPLE" VARCHAR2(255 BYTE), 
	"TEST_PAPER_NO" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into TEST.INFO_PAPER
REM INSERTING into TEST.STU_ANSWER
REM INSERTING into TEST.STU_INFO
Insert into TEST.STU_INFO (STU_INFO_ID,STU_INFO_NAME,STU_INFO_GRADE,STU_INFO_IDENTITY,STU_INFO_TICKET,STU_INFO_STA,STU_INFO_NO) values ('283','李问泽',null,'350301199201010012','100003',null,'ST-DG-C-001');
Insert into TEST.STU_INFO (STU_INFO_ID,STU_INFO_NAME,STU_INFO_GRADE,STU_INFO_IDENTITY,STU_INFO_TICKET,STU_INFO_STA,STU_INFO_NO) values ('284','黄榕城',null,'350301199201010013','100004',null,'ST-DG-C-001');
Insert into TEST.STU_INFO (STU_INFO_ID,STU_INFO_NAME,STU_INFO_GRADE,STU_INFO_IDENTITY,STU_INFO_TICKET,STU_INFO_STA,STU_INFO_NO) values ('285','陈艺伟',null,'350301199201010014','100005',null,'ST-DG-C-001');
Insert into TEST.STU_INFO (STU_INFO_ID,STU_INFO_NAME,STU_INFO_GRADE,STU_INFO_IDENTITY,STU_INFO_TICKET,STU_INFO_STA,STU_INFO_NO) values ('286','郑宜勤',null,'350301199201010015','100006',null,'ST-DG-C-001');
Insert into TEST.STU_INFO (STU_INFO_ID,STU_INFO_NAME,STU_INFO_GRADE,STU_INFO_IDENTITY,STU_INFO_TICKET,STU_INFO_STA,STU_INFO_NO) values ('287','罗文杰',null,'350301199201010016','100007',null,'ST-DG-C-001');
Insert into TEST.STU_INFO (STU_INFO_ID,STU_INFO_NAME,STU_INFO_GRADE,STU_INFO_IDENTITY,STU_INFO_TICKET,STU_INFO_STA,STU_INFO_NO) values ('288','林晓星',null,'350301199201010017','100008',null,'ST-DG-C-001');
Insert into TEST.STU_INFO (STU_INFO_ID,STU_INFO_NAME,STU_INFO_GRADE,STU_INFO_IDENTITY,STU_INFO_TICKET,STU_INFO_STA,STU_INFO_NO) values ('289','张晓勤',null,'350301199201010008','100009',null,'ST-DG-C-001');
Insert into TEST.STU_INFO (STU_INFO_ID,STU_INFO_NAME,STU_INFO_GRADE,STU_INFO_IDENTITY,STU_INFO_TICKET,STU_INFO_STA,STU_INFO_NO) values ('290','李亚彬',null,'350301199201010019','100010',null,'ST-DG-C-001');
Insert into TEST.STU_INFO (STU_INFO_ID,STU_INFO_NAME,STU_INFO_GRADE,STU_INFO_IDENTITY,STU_INFO_TICKET,STU_INFO_STA,STU_INFO_NO) values ('291','林怀杰',null,'350301199201010010','100001',null,'ST-DG-C-001');
Insert into TEST.STU_INFO (STU_INFO_ID,STU_INFO_NAME,STU_INFO_GRADE,STU_INFO_IDENTITY,STU_INFO_TICKET,STU_INFO_STA,STU_INFO_NO) values ('281','林怀杰',null,'350301199201010010','100001',null,'ST-DG-C-001');
Insert into TEST.STU_INFO (STU_INFO_ID,STU_INFO_NAME,STU_INFO_GRADE,STU_INFO_IDENTITY,STU_INFO_TICKET,STU_INFO_STA,STU_INFO_NO) values ('282','王倩',null,'350301199201010001','100002',null,'ST-DG-C-001');
Insert into TEST.STU_INFO (STU_INFO_ID,STU_INFO_NAME,STU_INFO_GRADE,STU_INFO_IDENTITY,STU_INFO_TICKET,STU_INFO_STA,STU_INFO_NO) values ('292','王倩',null,'350301199201010001','100002',null,'ST-DG-C-001');
Insert into TEST.STU_INFO (STU_INFO_ID,STU_INFO_NAME,STU_INFO_GRADE,STU_INFO_IDENTITY,STU_INFO_TICKET,STU_INFO_STA,STU_INFO_NO) values ('293','李问泽',null,'350301199201010012','100003',null,'ST-DG-C-001');
Insert into TEST.STU_INFO (STU_INFO_ID,STU_INFO_NAME,STU_INFO_GRADE,STU_INFO_IDENTITY,STU_INFO_TICKET,STU_INFO_STA,STU_INFO_NO) values ('294','黄榕城',null,'350301199201010013','100004',null,'ST-DG-C-001');
Insert into TEST.STU_INFO (STU_INFO_ID,STU_INFO_NAME,STU_INFO_GRADE,STU_INFO_IDENTITY,STU_INFO_TICKET,STU_INFO_STA,STU_INFO_NO) values ('295','陈艺伟',null,'350301199201010014','100005',null,'ST-DG-C-001');
Insert into TEST.STU_INFO (STU_INFO_ID,STU_INFO_NAME,STU_INFO_GRADE,STU_INFO_IDENTITY,STU_INFO_TICKET,STU_INFO_STA,STU_INFO_NO) values ('296','郑宜勤',null,'350301199201010015','100006',null,'ST-DG-C-001');
Insert into TEST.STU_INFO (STU_INFO_ID,STU_INFO_NAME,STU_INFO_GRADE,STU_INFO_IDENTITY,STU_INFO_TICKET,STU_INFO_STA,STU_INFO_NO) values ('297','罗文杰',null,'350301199201010016','100007',null,'ST-DG-C-001');
Insert into TEST.STU_INFO (STU_INFO_ID,STU_INFO_NAME,STU_INFO_GRADE,STU_INFO_IDENTITY,STU_INFO_TICKET,STU_INFO_STA,STU_INFO_NO) values ('298','林晓星',null,'350301199201010017','100008',null,'ST-DG-C-001');
Insert into TEST.STU_INFO (STU_INFO_ID,STU_INFO_NAME,STU_INFO_GRADE,STU_INFO_IDENTITY,STU_INFO_TICKET,STU_INFO_STA,STU_INFO_NO) values ('299','张晓勤',null,'350301199201010008','100009',null,'ST-DG-C-001');
Insert into TEST.STU_INFO (STU_INFO_ID,STU_INFO_NAME,STU_INFO_GRADE,STU_INFO_IDENTITY,STU_INFO_TICKET,STU_INFO_STA,STU_INFO_NO) values ('300','李亚彬',null,'350301199201010019','100010',null,'ST-DG-C-001');
REM INSERTING into TEST.TB_TEACHER
REM INSERTING into TEST.TEST_ANSWER
Insert into TEST.TEST_ANSWER (TEST_ANSWER_ID,TEST_ANSWER_NO,TEST_ANSWER_ANS,TEST_ANSWER_GRADE,TEST_ANSWER_TYPE,TEST_ANSWER_TIGAN,TEST_ANSWER_A,TEST_ANSWER_B,TEST_ANSWER_C,TEST_ANSWER_D,TEST_PAPER_ID) values ('418',' 103.0',' A,B,C',' 20','多选题',' 供电企业未按《电力法》和国家有关规定中规定时间通知用户或进行公告，而对用户中断供电，造成的损失应由(     )负责。',' 用户自己',' 电力管理部门',' 供电企业',' 发电企业','27');
Insert into TEST.TEST_ANSWER (TEST_ANSWER_ID,TEST_ANSWER_NO,TEST_ANSWER_ANS,TEST_ANSWER_GRADE,TEST_ANSWER_TYPE,TEST_ANSWER_TIGAN,TEST_ANSWER_A,TEST_ANSWER_B,TEST_ANSWER_C,TEST_ANSWER_D,TEST_PAPER_ID) values ('416',' 101.0',' A,B,C',' 20','多选题',' 未经许可，擅自伸入或跨越其他供电企业供电营业区供电者，由电力管理部门责令改正，没收违法所得，可以并处违法所得(     )以下的罚款。',' 三倍',' 四倍',' 五倍',' 五倍以上','27');
Insert into TEST.TEST_ANSWER (TEST_ANSWER_ID,TEST_ANSWER_NO,TEST_ANSWER_ANS,TEST_ANSWER_GRADE,TEST_ANSWER_TYPE,TEST_ANSWER_TIGAN,TEST_ANSWER_A,TEST_ANSWER_B,TEST_ANSWER_C,TEST_ANSWER_D,TEST_PAPER_ID) values ('417',' 102.0',' A,B,C',' 20','多选题',' 违反规定未取得电力业务许可证擅自经营电力业务的，由电力监管机构责令改正，没收违法所得，可以并处违法所得（    ）以下的罚款；构成犯罪的，依法追究刑事责任。',' 五倍',' 四倍',' 三倍',' 两倍','27');
Insert into TEST.TEST_ANSWER (TEST_ANSWER_ID,TEST_ANSWER_NO,TEST_ANSWER_ANS,TEST_ANSWER_GRADE,TEST_ANSWER_TYPE,TEST_ANSWER_TIGAN,TEST_ANSWER_A,TEST_ANSWER_B,TEST_ANSWER_C,TEST_ANSWER_D,TEST_PAPER_ID) values ('419',' 201.0',' C',' 20','单选题',' 违反电力法律，法规行为所应承担的法律责任包括（    ）。
',' 民事责任',' 行政责任',' 刑事责任',' 安全责任','27');
Insert into TEST.TEST_ANSWER (TEST_ANSWER_ID,TEST_ANSWER_NO,TEST_ANSWER_ANS,TEST_ANSWER_GRADE,TEST_ANSWER_TYPE,TEST_ANSWER_TIGAN,TEST_ANSWER_A,TEST_ANSWER_B,TEST_ANSWER_C,TEST_ANSWER_D,TEST_PAPER_ID) values ('420',' 202.0',' A',' 20','单选题',' 国家实行分类电价和分时电价,分类电价和分时办法不应由(     )确定',' 县人民政府',' 市人民政府',' 省人民政府',' 国务院','27');
Insert into TEST.TEST_ANSWER (TEST_ANSWER_ID,TEST_ANSWER_NO,TEST_ANSWER_ANS,TEST_ANSWER_GRADE,TEST_ANSWER_TYPE,TEST_ANSWER_TIGAN,TEST_ANSWER_A,TEST_ANSWER_B,TEST_ANSWER_C,TEST_ANSWER_D,TEST_PAPER_ID) values ('421',' 203.0',' C',' 20','单选题',' 国家对电力供应和使用，实行（    ）的管理原则。',' 安全用电',' 节约用电',' 计划用电',' 依法用电','27');
Insert into TEST.TEST_ANSWER (TEST_ANSWER_ID,TEST_ANSWER_NO,TEST_ANSWER_ANS,TEST_ANSWER_GRADE,TEST_ANSWER_TYPE,TEST_ANSWER_TIGAN,TEST_ANSWER_A,TEST_ANSWER_B,TEST_ANSWER_C,TEST_ANSWER_D,TEST_PAPER_ID) values ('422',' 204.0',' C',' 20','单选题',' 未经许可，擅自伸入或跨越其他供电企业供电营业区供电者，由电力管理部门责令改正，没收违法所得，可以并处违法所得(     )以下的罚款。',' 三倍',' 四倍',' 五倍',' 五倍以上','27');
Insert into TEST.TEST_ANSWER (TEST_ANSWER_ID,TEST_ANSWER_NO,TEST_ANSWER_ANS,TEST_ANSWER_GRADE,TEST_ANSWER_TYPE,TEST_ANSWER_TIGAN,TEST_ANSWER_A,TEST_ANSWER_B,TEST_ANSWER_C,TEST_ANSWER_D,TEST_PAPER_ID) values ('423',' 205.0',' A',' 20','单选题',' 违反规定未取得电力业务许可证擅自经营电力业务的，由电力监管机构责令改正，没收违法所得，可以并处违法所得（    ）以下的罚款；构成犯罪的，依法追究刑事责任。',' 五倍',' 四倍',' 三倍',' 两倍','27');
Insert into TEST.TEST_ANSWER (TEST_ANSWER_ID,TEST_ANSWER_NO,TEST_ANSWER_ANS,TEST_ANSWER_GRADE,TEST_ANSWER_TYPE,TEST_ANSWER_TIGAN,TEST_ANSWER_A,TEST_ANSWER_B,TEST_ANSWER_C,TEST_ANSWER_D,TEST_PAPER_ID) values ('424',' 206.0',' C',' 20','单选题',' 供电企业未按《电力法》和国家有关规定中规定时间通知用户或进行公告，而对用户中断供电，造成的损失应由(     )负责。',' 用户自己',' 电力管理部门',' 供电企业',' 发电企业','27');
Insert into TEST.TEST_ANSWER (TEST_ANSWER_ID,TEST_ANSWER_NO,TEST_ANSWER_ANS,TEST_ANSWER_GRADE,TEST_ANSWER_TYPE,TEST_ANSWER_TIGAN,TEST_ANSWER_A,TEST_ANSWER_B,TEST_ANSWER_C,TEST_ANSWER_D,TEST_PAPER_ID) values ('425',' 207.0',' C',' 20','单选题',' 未经许可，擅自伸入或跨越其他供电企业供电营业区供电者，由电力管理部门责令改正，没收违法所得，可以并处违法所得(     )以下的罚款。',' 三倍',' 四倍',' 五倍',' 五倍以上','27');
Insert into TEST.TEST_ANSWER (TEST_ANSWER_ID,TEST_ANSWER_NO,TEST_ANSWER_ANS,TEST_ANSWER_GRADE,TEST_ANSWER_TYPE,TEST_ANSWER_TIGAN,TEST_ANSWER_A,TEST_ANSWER_B,TEST_ANSWER_C,TEST_ANSWER_D,TEST_PAPER_ID) values ('426',' 208.0',' A',' 20','单选题',' 违反规定未取得电力业务许可证擅自经营电力业务的，由电力监管机构责令改正，没收违法所得，可以并处违法所得（    ）以下的罚款；构成犯罪的，依法追究刑事责任。',' 五倍',' 四倍',' 三倍',' 两倍','27');
Insert into TEST.TEST_ANSWER (TEST_ANSWER_ID,TEST_ANSWER_NO,TEST_ANSWER_ANS,TEST_ANSWER_GRADE,TEST_ANSWER_TYPE,TEST_ANSWER_TIGAN,TEST_ANSWER_A,TEST_ANSWER_B,TEST_ANSWER_C,TEST_ANSWER_D,TEST_PAPER_ID) values ('427',' 209.0',' C',' 20','单选题',' 供电企业未按《电力法》和国家有关规定中规定时间通知用户或进行公告，而对用户中断供电，造成的损失应由(     )负责。',' 用户自己',' 电力管理部门',' 供电企业',' 发电企业','27');
Insert into TEST.TEST_ANSWER (TEST_ANSWER_ID,TEST_ANSWER_NO,TEST_ANSWER_ANS,TEST_ANSWER_GRADE,TEST_ANSWER_TYPE,TEST_ANSWER_TIGAN,TEST_ANSWER_A,TEST_ANSWER_B,TEST_ANSWER_C,TEST_ANSWER_D,TEST_PAPER_ID) values ('428',' 210.0',' C',' 20','单选题',' 未经许可，擅自伸入或跨越其他供电企业供电营业区供电者，由电力管理部门责令改正，没收违法所得，可以并处违法所得(     )以下的罚款。',' 三倍',' 四倍',' 五倍',' 五倍以上','27');
Insert into TEST.TEST_ANSWER (TEST_ANSWER_ID,TEST_ANSWER_NO,TEST_ANSWER_ANS,TEST_ANSWER_GRADE,TEST_ANSWER_TYPE,TEST_ANSWER_TIGAN,TEST_ANSWER_A,TEST_ANSWER_B,TEST_ANSWER_C,TEST_ANSWER_D,TEST_PAPER_ID) values ('429',' 211.0',' A',' 20','单选题',' 违反规定未取得电力业务许可证擅自经营电力业务的，由电力监管机构责令改正，没收违法所得，可以并处违法所得（    ）以下的罚款；构成犯罪的，依法追究刑事责任。',' 五倍',' 四倍',' 三倍',' 两倍','27');
Insert into TEST.TEST_ANSWER (TEST_ANSWER_ID,TEST_ANSWER_NO,TEST_ANSWER_ANS,TEST_ANSWER_GRADE,TEST_ANSWER_TYPE,TEST_ANSWER_TIGAN,TEST_ANSWER_A,TEST_ANSWER_B,TEST_ANSWER_C,TEST_ANSWER_D,TEST_PAPER_ID) values ('430',' 212.0',' C',' 20','单选题',' 供电企业未按《电力法》和国家有关规定中规定时间通知用户或进行公告，而对用户中断供电，造成的损失应由(     )负责。',' 用户自己',' 电力管理部门',' 供电企业',' 发电企业','27');
REM INSERTING into TEST.TEST_PAPER
Insert into TEST.TEST_PAPER (TEST_PAPER_ID,TEST_PAPER_NAME,TEST_PAPER_GRADE,TEST_PAPER_WORK,TEST_PAPER_TYPE,TEST_PAPER_LEVEL,TEST_PAPER_TIME,TEST_PAPER_MECHANISM,TEST_PAPER_TEST,TEST_PAPER_SINGLE,TEST_PAPER_MULTIPLE,TEST_PAPER_NO) values ('105',' 电能表修校工初级理论知识试卷','[ST-DG-C-001',' 电能表修校工',' 市统考',' 初级作业员',' 120分钟',' 厦门市职业技能鉴定中心',null,' 一、单选题（第1～3 题。选择正确的答案，将相应的字母填入题内的括号中。每题20分。满分60分）：',' 二、多选题（第4～7 题。选择正确的答案，将相应的字母填入题内的括号中。每题20分。满分60分）：_]',' 60.0');
Insert into TEST.TEST_PAPER (TEST_PAPER_ID,TEST_PAPER_NAME,TEST_PAPER_GRADE,TEST_PAPER_WORK,TEST_PAPER_TYPE,TEST_PAPER_LEVEL,TEST_PAPER_TIME,TEST_PAPER_MECHANISM,TEST_PAPER_TEST,TEST_PAPER_SINGLE,TEST_PAPER_MULTIPLE,TEST_PAPER_NO) values ('106',' 电能表修校工初级理论知识试卷','[ST-DG-C-001',' 电能表修校工',' 市统考',' 初级作业员',' 120分钟',' 厦门市职业技能鉴定中心',null,' 一、单选题（第1～3 题。选择正确的答案，将相应的字母填入题内的括号中。每题20分。满分60分）：',' 二、多选题（第4～7 题。选择正确的答案，将相应的字母填入题内的括号中。每题20分。满分60分）：_]',' 60.0');
--------------------------------------------------------
--  DDL for Index STU_ANSWER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."STU_ANSWER_PK" ON "TEST"."STU_ANSWER" ("STU_ANSWER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index STU_INFO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."STU_INFO_PK" ON "TEST"."STU_INFO" ("STU_INFO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007106
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."SYS_C007106" ON "TEST"."TB_TEACHER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TEST_ANSWER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."TEST_ANSWER_PK" ON "TEST"."TEST_ANSWER" ("TEST_ANSWER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TEST_PAPER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."TEST_PAPER_PK" ON "TEST"."TEST_PAPER" ("TEST_PAPER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table STU_ANSWER
--------------------------------------------------------

  ALTER TABLE "TEST"."STU_ANSWER" ADD CONSTRAINT "STU_ANSWER_PK" PRIMARY KEY ("STU_ANSWER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TEST"."STU_ANSWER" MODIFY ("STU_ANSWER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STU_INFO
--------------------------------------------------------

  ALTER TABLE "TEST"."STU_INFO" ADD CONSTRAINT "STU_INFO_PK" PRIMARY KEY ("STU_INFO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TEST"."STU_INFO" MODIFY ("STU_INFO_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_TEACHER
--------------------------------------------------------

  ALTER TABLE "TEST"."TB_TEACHER" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TEST_ANSWER
--------------------------------------------------------

  ALTER TABLE "TEST"."TEST_ANSWER" ADD CONSTRAINT "TEST_ANSWER_PK" PRIMARY KEY ("TEST_ANSWER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TEST"."TEST_ANSWER" MODIFY ("TEST_ANSWER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TEST_PAPER
--------------------------------------------------------

  ALTER TABLE "TEST"."TEST_PAPER" ADD CONSTRAINT "TEST_PAPER_PK" PRIMARY KEY ("TEST_PAPER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TEST"."TEST_PAPER" MODIFY ("TEST_PAPER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table INFO_PAPER
--------------------------------------------------------

  ALTER TABLE "TEST"."INFO_PAPER" ADD CONSTRAINT "INFO_PAPER_STU_INFO_FK1" FOREIGN KEY ("STU_INFO_ID")
	  REFERENCES "TEST"."STU_INFO" ("STU_INFO_ID") ENABLE;
  ALTER TABLE "TEST"."INFO_PAPER" ADD CONSTRAINT "INFO_PAPER_TEST_PAPER_FK1" FOREIGN KEY ("TEST_PAPER_ID")
	  REFERENCES "TEST"."TEST_PAPER" ("TEST_PAPER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STU_ANSWER
--------------------------------------------------------

  ALTER TABLE "TEST"."STU_ANSWER" ADD CONSTRAINT "STU_ANSWER_TEST_PAPER_FK1" FOREIGN KEY ("TEST_PAPER_ID")
	  REFERENCES "TEST"."TEST_PAPER" ("TEST_PAPER_ID") ENABLE;
